---
- name: apt-get upgrade
  apt:
    upgrade: yes
    update_cache: yes
  become: yes   

- name: disable swap
  shell: swapoff -a
  become: yes

- name: Install required packages for docker
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  become: yes

- name: Add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add docker repo
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  become: yes

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Create Docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add user to the group
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes
  become: yes

- name: Add Kubernetes repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes

- name: Add Kubernetes repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    update_cache: yes
  become: yes

- name: Install kubernetes packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - kubelet
  - kubeadm
  - kubectl
  become: yes

- name: Hold kubernetes packages
  command: apt-mark hold kubelet kubeadm kubectl
  become: yes