---
 - name: Set net.bridge.bridge-nf-call-iptables=1
   shell: "sysctl net.bridge.bridge-nf-call-iptables=1"
   become: yes
   when: cni_network == "flannel"

 - name: Deploy Flannel
   when: cni_network == "flannel"
   command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml"
   register: flannel
   changed_when: '"created" in flannel.stdout'

 - name: Wait for Flannel deployment
   when: cni_network == "flannel"
   shell: "kubectl get pods --all-namespaces | grep -i CoreDNS"
   register: result
   until: result.stdout.find("Running") != -1
   retries: 60
   delay: 10
   changed_when: false